/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalmedyaişilanıtakibi;


import static sosyalmedyaişilanıtakibi.basvurularimPencere.bsvrPencere;
import static sosyalmedyaişilanıtakibi.girisPencere.gp1;
import static sosyalmedyaişilanıtakibi.ilanlarimPencere.ilanlarimP;
import static sosyalmedyaişilanıtakibi.iseklePencere.isekleP;
import static sosyalmedyaişilanıtakibi.isilanPencere.ilanlar;
import static sosyalmedyaişilanıtakibi.isilanPencere.kategoriliste;

/**
 *
 * @author dell
 */
public class anamenüPencere extends javax.swing.JFrame {

    /**
     * Creates new form anamenüPencere
     */
    public anamenüPencere() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jFrame1 = new javax.swing.JFrame();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        isekle_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        ilanim = new javax.swing.JButton();
        İsilanlari = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        ilanverjMenu4 = new javax.swing.JMenu();
        basvurularımjMenu5 = new javax.swing.JMenu();
        cıkısjMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        isekle_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isekle_btn.setText("İş İlanı ekle");
        isekle_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isekle_btnMouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Başvurularım");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Çıkış");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jEditorPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jEditorPane1.setText("Uygulamama Hoşgeldiniz Uygulamada  İş İlanlarını Takip edebilirsiniz");
        jScrollPane1.setViewportView(jEditorPane1);

        ilanim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ilanim.setText("İlanlarım");
        ilanim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ilanimMouseClicked(evt);
            }
        });

        İsilanlari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        İsilanlari.setText("İş İlanları");
        İsilanlari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                İsilanlariMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isekle_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ilanim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(İsilanlari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(İsilanlari)
                        .addGap(18, 18, 18)
                        .addComponent(isekle_btn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ilanim)))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jMenu1.setText("Anamenü");

        jMenu3.setText("İş İlanları");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu3);

        ilanverjMenu4.setText("İlan Ver");
        ilanverjMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ilanverjMenu4MouseClicked(evt);
            }
        });
        jMenu1.add(ilanverjMenu4);

        basvurularımjMenu5.setText("Başvurularım");
        basvurularımjMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                basvurularımjMenu5MouseClicked(evt);
            }
        });
        jMenu1.add(basvurularımjMenu5);

        cıkısjMenuItem2.setText("Çıkış");
        cıkısjMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cıkısjMenuItem2MouseClicked(evt);
            }
        });
        jMenu1.add(cıkısjMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    static anamenüPencere ana=new anamenüPencere();
    private void İsilanlariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_İsilanlariMouseClicked
        // TODO add your handling code here:
        ana.setVisible(false);
         
        ilanlar.show();
        ilanlar.combo();
    }//GEN-LAST:event_İsilanlariMouseClicked

    private void isekle_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isekle_btnMouseClicked
        // TODO add your handling code here:
        ana.setVisible(false);
        isekleP.show();
    }//GEN-LAST:event_isekle_btnMouseClicked

    private void ilanimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilanimMouseClicked
        // TODO add your handling code here:
        ana.setVisible(false);
        ilanlarimP.show();
    }//GEN-LAST:event_ilanimMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ana.setVisible(false);
        gp1.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: Başvurularım
        ana.setVisible(false);
        bsvrPencere.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
          ana.setVisible(false);
         
        ilanlar.show();
        ilanlar.combo();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void ilanverjMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilanverjMenu4MouseClicked
        // TODO add your handling code here:
        ana.setVisible(false);
        isekleP.show();
    }//GEN-LAST:event_ilanverjMenu4MouseClicked

    private void basvurularımjMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basvurularımjMenu5MouseClicked
        // TODO add your handling code here:
         ana.setVisible(false);
        bsvrPencere.show();
    }//GEN-LAST:event_basvurularımjMenu5MouseClicked

    private void cıkısjMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cıkısjMenuItem2MouseClicked
        // TODO add your handling code here:
        ana.setVisible(false);
        gp1.show();
    }//GEN-LAST:event_cıkısjMenuItem2MouseClicked
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anamenüPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anamenüPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anamenüPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anamenüPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new anamenüPencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu basvurularımjMenu5;
    private javax.swing.JMenuItem cıkısjMenuItem2;
    private javax.swing.JButton ilanim;
    private javax.swing.JMenu ilanverjMenu4;
    private javax.swing.JButton isekle_btn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JButton İsilanlari;
    // End of variables declaration//GEN-END:variables
}
