/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalmedyaişilanıtakibi;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static sosyalmedyaişilanıtakibi.anamenüPencere.ana;
import static sosyalmedyaişilanıtakibi.iseklePencere.isilan;
import static sosyalmedyaişilanıtakibi.İsİlani.baslık;
import static sosyalmedyaişilanıtakibi.İsİlani.basvurudurum;

/**
 *
 * @author dell
 */
public class basvurularimPencere extends javax.swing.JFrame {

    /**
     * Creates new form basvurularimPencere
     */
    DefaultTableModel dtm=new DefaultTableModel();
    public basvurularimPencere() {
        initComponents();
        basvurularımjTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new String[] {"id","İsBaslıgı","Durum"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        basvuruListele = new javax.swing.JButton();
        geri_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        basvurularımjTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(211, 211, 211));

        basvuruListele.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        basvuruListele.setText("Başvurularımı");
        basvuruListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basvuruListeleActionPerformed(evt);
            }
        });

        geri_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        geri_btn.setText("Geri");
        geri_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_btnActionPerformed(evt);
            }
        });

        basvurularımjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "İş Başlığı", "Durum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(basvurularımjTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(geri_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basvuruListele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(basvuruListele)
                .addGap(18, 18, 18)
                .addComponent(geri_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//İsİlani isim2=new İsİlani();
static basvurularimPencere bsvrPencere =new basvurularimPencere();
    private void basvuruListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basvuruListeleActionPerformed
        // TODO add your handling code here:
        
         int i;
        String id,bslk,durum;
        //basvurudurum.add("");
        try {
             System.out.print("yer");
           while(dtm.getRowCount()>0)
            {
                for(i=0;i<dtm.getRowCount();i++)
                    dtm.removeRow(i);
            }
            isilan.basvurugöster();
           
             for(i=0;i<baslık.size();i++)
            {
                bslk=(String)baslık.get(i);
                durum=(String)basvurudurum.get(i);
                if(durum=="1")
                    durum="Basvurunuz kabul edildi";
                else
                    durum="Başvuru sonucu bekleniyor";
                 id=String.valueOf((i+1));
                dtm.addRow(new String []{id,bslk,durum});
             
            }
      

        }
        
           catch(SQLException e)
        {
            System.out.println("Bir sorun yaşadık");
            System.out.println(e);
          
        }
       
        
    }//GEN-LAST:event_basvuruListeleActionPerformed

    private void geri_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_btnActionPerformed
        // TODO add your handling code here:
        bsvrPencere.setVisible(false);
        ana.show();
    }//GEN-LAST:event_geri_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basvurularimPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basvurularimPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basvurularimPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basvurularimPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basvurularimPencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basvuruListele;
    private javax.swing.JTable basvurularımjTable1;
    private javax.swing.JButton geri_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
