/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalmedyaişilanıtakibi;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static sosyalmedyaişilanıtakibi.anamenüPencere.ana;
import static sosyalmedyaişilanıtakibi.iseklePencere.isilan;
import static sosyalmedyaişilanıtakibi.İsİlani.baslık;

/**
 *
 * @author dell
 */
public class ilanlarimPencere extends javax.swing.JFrame {

    /**
     * Creates new form ilanlarimPencere
     */
    DefaultTableModel dtm=new DefaultTableModel();
    public ilanlarimPencere() {
        initComponents();
        ilanlarimjTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new String[] {"id","İsBaslıgı","Başvuranlar"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ilanlarimiListele = new javax.swing.JButton();
        geri_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ilanlarimjTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        iseal_btn = new javax.swing.JButton();
        isealimnacakkisi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(211, 211, 211));

        ilanlarimiListele.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ilanlarimiListele.setText("Listele");
        ilanlarimiListele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ilanlarimiListeleMouseClicked(evt);
            }
        });

        geri_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        geri_btn.setText("Geri");
        geri_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geri_btnMouseClicked(evt);
            }
        });

        ilanlarimjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "İş Başlığı", "Başvuranlar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ilanlarimjTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setText("İşinizi tabloda seçtikten sonra işe almak istediğiniz elemanın ismini giriniz");

        iseal_btn.setText("İşe Al");
        iseal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iseal_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ilanlarimiListele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(geri_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isealimnacakkisi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(iseal_btn)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ilanlarimiListele)
                        .addGap(18, 18, 18)
                        .addComponent(geri_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iseal_btn)
                    .addComponent(isealimnacakkisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   static ilanlarimPencere ilanlarimP=new ilanlarimPencere();
   // İsİlani isim1=new İsİlani();
    private void ilanlarimiListeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilanlarimiListeleMouseClicked
        // TODO add your handling code here:
      
        int i;
        String id,bslk,basvuran;
        try {
            while(dtm.getRowCount()>0)
            {
                for(i=0;i<dtm.getRowCount();i++)
                    dtm.removeRow(i);
            }
             isilan.ilangöster();
            
            String  basvuranlar="";
             for(i=0;i<baslık.size();i++)
            {
                bslk=(String) baslık.get(i);
                basvuran=isilan.basvuranlar(bslk);
                id=String.valueOf((i+1));
                dtm.addRow(new String []{id,bslk,basvuran});
             
            }
      

        } catch (SQLException ex) {
            Logger.getLogger(isilanPencere.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_ilanlarimiListeleMouseClicked

    private void geri_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geri_btnMouseClicked
        // TODO add your handling code here:
        ilanlarimP.setVisible(false);
        ana.show();
    }//GEN-LAST:event_geri_btnMouseClicked

    private void iseal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iseal_btnActionPerformed
        // TODO add your handling code here:
        int tableindis;
        String ise_alinacak_kisi,hata,bslk;
        
        try {
            
            tableindis=ilanlarimjTable1.getSelectedRow();
        ise_alinacak_kisi=isealimnacakkisi.getText();
        bslk=baslık.get(tableindis);
            hata=isilan.ise_al(bslk,ise_alinacak_kisi);
            System.out.print(hata);
        } catch (SQLException ex) {
            Logger.getLogger(ilanlarimPencere.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iseal_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ilanlarimPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ilanlarimPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ilanlarimPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ilanlarimPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ilanlarimPencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geri_btn;
    private javax.swing.JButton ilanlarimiListele;
    private javax.swing.JTable ilanlarimjTable1;
    private javax.swing.JButton iseal_btn;
    private javax.swing.JTextField isealimnacakkisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
