/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalmedyaişilanıtakibi;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static sosyalmedyaişilanıtakibi.anamenüPencere.ana;
import static sosyalmedyaişilanıtakibi.iseklePencere.isilan;
import static sosyalmedyaişilanıtakibi.İsİlani.baslık;
import static sosyalmedyaişilanıtakibi.İsİlani.isil;

/**
 *
 * @author dell
 */
public class isilanPencere extends javax.swing.JFrame {

    private TableModel model;

    /**
     * Creates new form isilanPencere
     */
     DefaultTableModel dtm=new DefaultTableModel();
    public isilanPencere() {
        initComponents();
        jTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new String[] {"id","İsBaslıgı","Şehir"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        geri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kategori_box = new javax.swing.JComboBox<>();
        Listele = new javax.swing.JButton();
        basvur = new javax.swing.JButton();
        bildirim_txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(211, 211, 211));

        geri.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        geri.setText("Geri");
        geri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriMouseClicked(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(211, 211, 211));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "İsBaslıgı", "Şehir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        kategori_box.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kategori_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bilisim", "Sağlık", "Satiş", " " }));

        Listele.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Listele.setText("Listele");
        Listele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeleMouseClicked(evt);
            }
        });

        basvur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        basvur.setText("Başvur");
        basvur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                basvurMouseClicked(evt);
            }
        });

        bildirim_txt.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        bildirim_txt.setForeground(new java.awt.Color(3, 139, 60));
        bildirim_txt.setText("hh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(geri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Listele, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basvur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(kategori_box, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(bildirim_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kategori_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(Listele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(basvur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(geri))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bildirim_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 static  ArrayList<String> kategoriliste=new ArrayList();
//static  İsİlani isilanListe=new İsİlani();


    private void ListeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeleMouseClicked
        // TODO add your handling code here:
       int sira=0,i;
       String id;
       
       sira=kategori_box.getSelectedIndex( );

      
       try {
            while(dtm.getRowCount()>0)
            {
                for(i=0;i<dtm.getRowCount();i++)
                    dtm.removeRow(i);
            }
             isilan.ilangöster(kategoriliste.get(sira));
            String bslk[]=new String[baslık.size()];
            String ildizi[]=new String[isil.size()];
          //  ilanlar.deleteAllRows(model);
             for(i=0;i<baslık.size();i++)
            {
                bslk[i]=(String) baslık.get(i);
                ildizi[i]=(String) isil.get(i);
                 id=String.valueOf((i+1));
                dtm.addRow(new String []{id,bslk[i],ildizi[i]});
             
            }
      

        } catch (SQLException ex) {
            Logger.getLogger(isilanPencere.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
        
    }//GEN-LAST:event_ListeleMouseClicked

    private void geriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriMouseClicked
        // TODO add your handling code here:
        ilanlar.setVisible(false);
         ilanlar.setVisible(false);
        ana.show();
    }//GEN-LAST:event_geriMouseClicked

    private void basvurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basvurMouseClicked
        // TODO add your handling code here:
        int basvuruindis=0;
        String mesaj="";
        basvuruindis=jTable1.getSelectedRow();
        
        mesaj=isilan.basvuruekle(basvuruindis);
        bildirim_txt.setText("");
        bildirim_txt.setText(mesaj);
        
            
        
    }//GEN-LAST:event_basvurMouseClicked
static isilanPencere ilanlar =new isilanPencere();

    /**
     *
     */
    static void combo()
    {
        
        int i;
        ilanlar.kategori_box.removeAllItems( );

         
         isilan.kategoriListesi();
        for(i=0;i<kategoriliste.size();i++)
            ilanlar.kategori_box.addItem(kategoriliste.get(i));
    }    
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(isilanPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(isilanPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(isilanPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(isilanPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new isilanPencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Listele;
    private javax.swing.JButton basvur;
    private javax.swing.JLabel bildirim_txt;
    private javax.swing.JButton geri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> kategori_box;
    // End of variables declaration//GEN-END:variables


}
